Algoritmo "Conversão de Distância"

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/09/2026

Var

km, hm, dam, m, dm, cm, mm: Real

Inicio

Escreva ("Informe a sua medida em Metros: ")
Leia (m)
km <- (m / 1000)
hm <- (m / 100)
dam <- (m / 10)
dm <- (m * 10)
cm <- (m * 100)
mm <- (m * 1000)
Escreval ("A distância de ", m, "m coresponde a: ")
Escreval (km, " km")
Escreval (hm, " hm")
Escreval (dam, " dam")
Escreval (dm, " dm")
Escreval (cm, " cm")
Escreval (mm, " mm")

Fimalgoritmo