Algoritmo "Média de Nota"

// Autor(a)    : Klem
// Data atual  : 07/09/2026

Var

// Declaração das Variáveis
nota1, nota2, media: Real

Inicio

// Inserimento das Notas
Escreva ("Insira a sua 1° Nota: ")
Leia (nota1)
Escreva ("Insira a sua 2° Nota: ")
Leia (nota2)

// Fazer a soma e a media; e atribuir ela a variável Media
media <- (nota1 + nota2)/2

// Exibição da Media
Escreva ("A Média de ", nota1, " e ", nota2, " é igual a: ", media)

Fimalgoritmo