Algoritmo "Soma de 2 Números"

// Autor(a)    : Klem
// Data atual  : 07/09/2026

Var

// Declaração das Variáveis
n1, n2, soma: Real

Inicio

// Inserimento dos 2 Números
Escreva ("Insira o 1° Número: ")
Leia (n1)
Escreva ("Insira o 2° Número: ")
Leia (n2)

// Fazer a soma e atribuir ela a variável Soma
soma <- n1+n2

// Exibição da Soma
Escreva ("A soma de ", n1, " + ", n2, " é igual a: ", soma)

Fimalgoritmo